
package corehealth;

import dbaccess.Course;
import dbaccess.CourseMember;
import dbaccess.CourseMemberService;
import dbaccess.CourseService;
import dbaccess.DataAccessException;
import dbaccess.Member;
import dbaccess.MemberService;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * JFrame that has the GUI and communicates with the database service object,
 * and handles all exceptions and displaying of information, error messages,
 * confirmation screens. Basic function is a have user input ID, and course ID
 * to sign them up for a class.
 * 
 * @author Andy
 */
public class CourseWindow extends javax.swing.JFrame {

    /**
     * Creates new form CourseWindow
     */
    public CourseWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMemberId = new javax.swing.JTextField();
        txtCourseId = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        btnClearMemberId = new javax.swing.JButton();
        btnClearCourseId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ez Swipe 1.0");
        setBounds(new java.awt.Rectangle(500, 250, 375, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apex Business Solutions 2013", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Member Id:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Course Id:");

        txtMemberId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtCourseId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnClearMemberId.setText("Clear");
        btnClearMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearMemberIdActionPerformed(evt);
            }
        });

        btnClearCourseId.setText("Clear");
        btnClearCourseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCourseIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearMemberId))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearCourseId)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearMemberId))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearCourseId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
 
        try {

            final String WEL = "Welcome to Core Health!";
            final Icon muscle = new ImageIcon("icons/muscle.jpg");
            final String MAIN_CONFIG = "spring/mainConfig.xml";
            
            final String MEM_SERVICE_BEAN = "memberService";
            final String COURSE_SERV_BEAN = "courseService";
            final String COURSE_MEM_SERV_BEAN = "courseMemberService";
            
            final String MEMBER_BEAN = "member";
            final String COURSE_BEAN = "course";
            final String COURSE_MEM_BEAN = "courseMember";
            
            final String SWIPE_BEAN = "swipeWindow";
            
            String sMemberId = txtMemberId.getText();
            String sCourseId = txtCourseId.getText();
            int memberId = Integer.valueOf(sMemberId);
            int courseId = Integer.valueOf(sCourseId);
            
            AbstractApplicationContext context
                    = new ClassPathXmlApplicationContext(new String[] {MAIN_CONFIG});
            
            MemberService memServ = (MemberService)context.getBean(MEM_SERVICE_BEAN);
            CourseService courseServ = (CourseService)context.getBean(COURSE_SERV_BEAN);
            CourseMemberService courseMemServ = 
                    (CourseMemberService)context.getBean(COURSE_MEM_SERV_BEAN);
            
            
            Member member = (Member)context.getBean(MEMBER_BEAN);
            Course course = (Course)context.getBean(COURSE_BEAN);
            CourseMember courseMem = (CourseMember)context.getBean(COURSE_MEM_BEAN);

            
            if (member == null || sMemberId == null ||
                    course == null || sCourseId == null){
                
                throw new NullPointerException();
                
            } else {
                
            member = memServ.getMemberById(sMemberId);
            course = courseServ.getCourseById(sCourseId);


                JOptionPane.showMessageDialog(this, "Welcome Back,  " +
                        member.getFirstName() + " " + member.getLastName() +
                        "!" , WEL , JOptionPane.PLAIN_MESSAGE, muscle);
            
            System.out.println(courseServ.getCourseById(sCourseId));
        
            }
            
        
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "Invalid. Please See An Employee", null, JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        } catch (DataAccessException dae) {
            JOptionPane.showMessageDialog(this, dae.getMessage(), null, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnClearMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearMemberIdActionPerformed
        // TODO add your handling code here:
        
        txtMemberId.setText(null);
    }//GEN-LAST:event_btnClearMemberIdActionPerformed

    private void btnClearCourseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCourseIdActionPerformed
        // TODO add your handling code here:
        
        txtCourseId.setText(null);
    }//GEN-LAST:event_btnClearCourseIdActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CourseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CourseWindow().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCourseId;
    private javax.swing.JButton btnClearMemberId;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtMemberId;
    // End of variables declaration//GEN-END:variables
}
